/*
 * This file was generated by the Gradle 'init' task.
 */

group = "com.artillexstudios"
version = "1.26.4"
description = "AxGraves"
java.sourceCompatibility = JavaVersion.VERSION_21
var mainMinecraftVersion = "1.21.11"
val supportedMinecraftVersions = "1.20 - 1.21.11"


val mvndiRemote = repositories.maven("https://repo.mvndicraft.net/repository/maven-snapshots/") {
    name = "Mvndi"
    credentials {
        username = project.findProperty("mvndi.user") as String? ?: System.getenv("MVNDI_MVN_USER")
        password = project.findProperty("mvndi.key") as String? ?: System.getenv("MVNDI_MVN_KEY")
    }
}

plugins {
    `java-library`
    id("com.gradleup.shadow") version "8.3.8"
    id("xyz.jpenilla.run-paper") version "2.3.1"
}


repositories {
    maven {
        url = uri("https://repo.artillex-studios.com/releases/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    mvndiRemote
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://jitpack.io")
    maven("https://repo.aikar.co/content/groups/aikar/")
    maven("https://repo.glaremasters.me/repository/towny/")
    
}

dependencies {
    implementation("com.artillexstudios.axapi:axapi:1.4.840:all")
    implementation("com.github.ben-manes.caffeine:caffeine:3.1.8")
    implementation(libs.org.bstats.bstats.bukkit)
    compileOnly("io.papermc.paper:paper-api:$mainMinecraftVersion-R0.1-SNAPSHOT")
    compileOnly(libs.org.slf4j.slf4j.api)
    compileOnly("com.github.TownyAdvanced:Towny:0.102.0.0") {
        exclude(group = "org.bukkit", module = "bukkit")
    }
    compileOnly("com.github.TownyAdvanced:SiegeWar:2.19.3") {
        exclude(group = "org.bukkit", module = "bukkit")
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.processResources {
    filteringCharset = "UTF-8"
    filesMatching("plugin.yml") {
        filter {
            it.replace("\${project.version}", project.version.toString())
        }
    }
}

tasks.jar {
    archiveClassifier.set("plain")
}

tasks.named<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("shadowJar") {
    archiveClassifier.set("")
    relocate("com.github.benmanes.caffeine", "com.artillexstudios.axgraves.libs.axapi.libs.caffeine.caffeine")
    relocate("com.artillexstudios.axapi", "com.artillexstudios.axgraves.libs.axapi")
    relocate("org.bstats", "com.artillexstudios.axgraves.libs.bstats")
    relocate("revxrsal.commands", "com.artillexstudios.axgraves.libs.lamp")
    exclude("META-INF/*.SF", "META-INF/*.DSA", "META-INF/*.RSA")
}

tasks.matching { it.name == "runServer" || it.name == "runFolia" }.configureEach {
    dependsOn(tasks.named("shadowJar"))
}

tasks {
    assemble {
        dependsOn(shadowJar)
    }
    runServer {
        minecraftVersion("$mainMinecraftVersion")
    }
    runPaper.folia.registerTask()
}