/*
 * This file was generated by the Gradle 'init' task.
 */

group = "com.artillexstudios"
version = "1.26.2"
description = "AxGraves"
java.sourceCompatibility = JavaVersion.VERSION_21
var mainMinecraftVersion = "1.21.11"
val supportedMinecraftVersions = "1.20 - 1.21.11"

plugins {
    `java-library`
    `maven-publish`
    id("xyz.jpenilla.run-paper") version "2.3.1"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }
    maven {
        url = uri("https://repo.artillex-studios.com/releases/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("com.artillexstudios.axapi:axapi:1.4.840:all")
    api(libs.org.bstats.bstats.bukkit)
    compileOnly("io.papermc.paper:paper-api:$mainMinecraftVersion-R0.1-SNAPSHOT")
    compileOnly(libs.org.slf4j.slf4j.api)
}



publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks {
    runServer {
        minecraftVersion("$mainMinecraftVersion")
    }
    runPaper.folia.registerTask()
}